name: CI Security Checks

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit pip-audit

    - name: Run Bandit (SAST)
      run: bandit -r .

    - name: Run pip-audit (SCA)
      run: pip-audit --fail-on high

    - name: Install GitLeaks
      run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks-linux-amd64.tar.gz | tar -xz
        sudo mv gitleaks /usr/local/bin/

    - name: Run GitLeaks (Secrets scan)
      run: gitleaks detect --verbose

    - name: Build Docker image
      run: docker build -t myapp .
